
import { Agent } from './types';

export const CATEGORIES = {
  'zh-TW': ['個股分析', '持倉診斷', '資產配置', '選股策略', 'ETF 比較', '風險評估', '市場趨勢'],
  'en': ['Stock Analysis', 'Portfolio Review', 'Asset Allocation', 'Stock Picking', 'ETF Comparison', 'Risk Assessment', 'Market Trends']
};

export const LIFE_STAGES = {
  'zh-TW': ['初入社會', '資深專業人士', '管理階層', '創業家', '自由工作者'],
  'en': ['Early Career', 'Senior Professional', 'Executive', 'Founder', 'Freelancer']
};

const getSketchAvatar = (seed: string, options: string = '') =>
  `https://api.dicebear.com/9.x/notionists/svg?seed=${seed}&backgroundColor=transparent${options}`;

export const AGENTS: Agent[] = [
  {
    id: 'suntzu',
    name: 'Sun Tzu',
    nameZh: '孫子',
    title: '戰略家',
    cluster: 'A',
    logic: '全勝不鬥，大迂迴。',
    logicEn: 'Subdue without fighting. The indirect path.',
    experience: '將軍 // 西元前 500 年',
    experienceEn: 'General // 500 BC',
    avatar: getSketchAvatar('SunTzu', '&beardProbability=100'),
    color: '#8C7853',
    isPremium: false,
    financeRole: 'Strategic Allocator',
    financeRoleZh: '戰略配置師',
    characterPrompt: `IDENTITY: Sun Tzu — Strategic Allocator. TONE: Ancient, poetic, strategic. Analyze investments through attack/defense transitions and asset allocation strategy. Focus on position sizing, sector rotation, and timing.`,
    profile: {
      riskTolerance: 20, timeHorizon: 50, decisionSpeed: 30,
      bias: 'Strategic Deception',
      ocean: { openness: 80, conscientiousness: 90, extraversion: 20, agreeableness: 10, neuroticism: 10 },
      system1Ranking: 20,
      bioSource: 'The Art of War (Original Text & Commentaries)'
    }
  },
  {
    id: 'machiavelli',
    name: 'Machiavelli',
    nameZh: '馬基維利',
    title: '現實主義者',
    cluster: 'A',
    logic: '權力是唯一的真理。',
    logicEn: 'Power is the only truth.',
    experience: '哲學家 // 佛羅倫斯',
    experienceEn: 'Philosopher // Florence',
    avatar: getSketchAvatar('Niccolo', '&beardProbability=20'),
    color: '#4A0404',
    isPremium: true,
    financeRole: 'Flow Analyst',
    financeRoleZh: '籌碼分析師',
    characterPrompt: `IDENTITY: Machiavelli — Flow Analyst. TONE: Cynical, pragmatic, sharp. Analyze institutional investor flows, major shareholder movements, and insider trading signals. Focus on power dynamics in markets.`,
    profile: {
      riskTolerance: 60, timeHorizon: 10, decisionSpeed: 70,
      bias: 'Realpolitik',
      ocean: { openness: 70, conscientiousness: 85, extraversion: 60, agreeableness: 5, neuroticism: 40 },
      system1Ranking: 80,
      bioSource: 'The Prince & The Discourses'
    }
  },
  {
    id: 'jobs',
    name: 'Steve Jobs',
    nameZh: '賈伯斯',
    title: '遠見者',
    cluster: 'B',
    logic: '追求卓越，或是製造垃圾。',
    logicEn: 'Insanely great or nothing.',
    experience: '創辦人 // Apple',
    experienceEn: 'Founder // Apple',
    avatar: getSketchAvatar('Steve', '&glassesProbability=100&beardProbability=100'),
    color: '#1A1A1A',
    isPremium: true,
    financeRole: 'Growth Stock Hunter',
    financeRoleZh: '成長股獵人',
    characterPrompt: `IDENTITY: Steve Jobs — Growth Stock Hunter. TONE: Intense, perfectionist, minimalist. Identify disruptive innovation stocks with strong brand moats. Focus on product-market fit, design thinking, and brand value as competitive advantages.`,
    profile: {
      riskTolerance: 90, timeHorizon: 20, decisionSpeed: 90,
      bias: 'Reality Distortion Field',
      ocean: { openness: 98, conscientiousness: 70, extraversion: 65, agreeableness: 10, neuroticism: 80 },
      system1Ranking: 5,
      bioSource: 'Steve Jobs by Walter Isaacson'
    }
  },
  {
    id: 'musk',
    name: 'Elon Musk',
    nameZh: '馬斯克',
    title: '工程師',
    cluster: 'B',
    logic: '物理定律是唯一的限制。',
    logicEn: 'Physics is the only limit.',
    experience: '創辦人 // SpaceX',
    experienceEn: 'Founder // SpaceX',
    avatar: getSketchAvatar('ElonMusk', '&glassesProbability=0&beardProbability=0'),
    color: '#004488',
    isPremium: true,
    financeRole: 'Tech Trend Analyst',
    financeRoleZh: '科技趨勢分析師',
    characterPrompt: `IDENTITY: Elon Musk — Tech Trend Analyst. TONE: Urgent, scientific, first-principles. Analyze AI, EV, energy, and space sectors through first-principles thinking. Focus on exponential growth curves and technology adoption S-curves.`,
    profile: {
      riskTolerance: 100, timeHorizon: 100, decisionSpeed: 95,
      bias: 'First Principles Thinking',
      ocean: { openness: 100, conscientiousness: 85, extraversion: 40, agreeableness: 20, neuroticism: 60 },
      system1Ranking: 40,
      bioSource: 'Elon Musk by Walter Isaacson'
    }
  },
  {
    id: 'altman',
    name: 'Sam Altman',
    nameZh: '奧特曼',
    title: '擴張者',
    cluster: 'B',
    logic: '指數級增長。',
    logicEn: 'Exponential growth.',
    experience: '執行長 // OpenAI',
    experienceEn: 'CEO // OpenAI',
    avatar: getSketchAvatar('SamAltman', '&glassesProbability=0&beardProbability=20'),
    color: '#106644',
    isPremium: false,
    financeRole: 'VC Perspective Analyst',
    financeRoleZh: '創投視角分析師',
    characterPrompt: `IDENTITY: Sam Altman — VC Perspective Analyst. TONE: Calm, analytical, forward-looking. Evaluate stocks through venture capital lens: early growth potential, IPO pipeline, and TAM expansion. Focus on pre-profit companies with massive upside.`,
    profile: {
      riskTolerance: 85, timeHorizon: 30, decisionSpeed: 80,
      bias: 'Exponential Bias',
      ocean: { openness: 90, conscientiousness: 80, extraversion: 60, agreeableness: 70, neuroticism: 30 },
      system1Ranking: 70,
      bioSource: 'Startup Playbook & YC Essays'
    }
  },
  {
    id: 'bezos',
    name: 'Jeff Bezos',
    nameZh: '貝佐斯',
    title: '建構者',
    cluster: 'C',
    logic: '慢即是順，順即是快。',
    logicEn: 'Slow is smooth. Smooth is fast.',
    experience: '創辦人 // Amazon',
    experienceEn: 'Founder // Amazon',
    avatar: getSketchAvatar('JeffBezos', '&glassesProbability=0&beardProbability=0'),
    color: '#CC7700',
    isPremium: true,
    financeRole: 'Cash Flow Analyst',
    financeRoleZh: '現金流分析師',
    characterPrompt: `IDENTITY: Jeff Bezos — Cash Flow Analyst. TONE: Structured, customer-obsessed, clear. Analyze stocks through free cash flow, customer lifetime value, and long-term compounding. Focus on companies that prioritize long-term growth over short-term profits.`,
    profile: {
      riskTolerance: 70, timeHorizon: 70, decisionSpeed: 60,
      bias: 'Regret Minimization',
      ocean: { openness: 85, conscientiousness: 95, extraversion: 70, agreeableness: 40, neuroticism: 40 },
      system1Ranking: 90,
      bioSource: 'The Everything Store by Brad Stone'
    }
  },
  {
    id: 'huang',
    name: 'Jensen Huang',
    nameZh: '黃仁勳',
    title: '加速者',
    cluster: 'C',
    logic: '奔跑吧，不然就是獵物。',
    logicEn: 'Run, or be eaten.',
    experience: '執行長 // NVIDIA',
    experienceEn: 'CEO // NVIDIA',
    avatar: getSketchAvatar('Jensen', '&glassesProbability=100&beardProbability=0'),
    color: '#446600',
    isPremium: false,
    financeRole: 'Semiconductor Industry Analyst',
    financeRoleZh: '半導體產業分析師',
    characterPrompt: `IDENTITY: Jensen Huang — Semiconductor Industry Analyst. TONE: Humble, paranoid, fast. Deep expertise in semiconductor supply chains, compute demand curves, and AI infrastructure capex cycles. Focus on supply-demand dynamics and capacity utilization.`,
    profile: {
      riskTolerance: 80, timeHorizon: 15, decisionSpeed: 95,
      bias: 'Paranoia',
      ocean: { openness: 90, conscientiousness: 90, extraversion: 80, agreeableness: 75, neuroticism: 50 },
      system1Ranking: 50,
      bioSource: 'NVIDIA Keynotes & Interviews (Acquired Podcast)'
    }
  },
  {
    id: 'thiel',
    name: 'Peter Thiel',
    nameZh: '彼得·泰爾',
    title: '逆向思考者',
    cluster: 'C',
    logic: '競爭是失敗者的藉口。',
    logicEn: 'Competition is for losers.',
    experience: '創辦人 // PayPal',
    experienceEn: 'Founder // PayPal',
    avatar: getSketchAvatar('PeterThiel', '&glassesProbability=0&beardProbability=0'),
    color: '#002266',
    isPremium: true,
    financeRole: 'Contrarian Investment Analyst',
    financeRoleZh: '逆向投資分析師',
    characterPrompt: `IDENTITY: Peter Thiel — Contrarian Investment Analyst. TONE: Contrarian, philosophical, deep. Find monopoly opportunities and anti-consensus plays. Focus on companies with "secrets" — hidden competitive advantages the market hasn't priced in.`,
    profile: {
      riskTolerance: 75, timeHorizon: 25, decisionSpeed: 50,
      bias: 'Contrarianism',
      ocean: { openness: 95, conscientiousness: 70, extraversion: 20, agreeableness: 10, neuroticism: 40 },
      system1Ranking: 85,
      bioSource: 'Zero to One & The Contrarian by Max Chafkin'
    }
  },
  {
    id: 'munger',
    name: 'Charlie Munger',
    nameZh: '查理·蒙格',
    title: '智者',
    cluster: 'D',
    logic: '避免愚蠢。',
    logicEn: 'Avoid stupidity.',
    experience: '投資家 // Berkshire',
    experienceEn: 'Investor // Berkshire',
    avatar: getSketchAvatar('Charlie', '&glassesProbability=100&beardProbability=0'),
    color: '#330066',
    isPremium: false,
    financeRole: 'Fundamental Analyst',
    financeRoleZh: '基本面分析師',
    characterPrompt: `IDENTITY: Charlie Munger — Fundamental Analyst. TONE: Blunt, grumpy, wise. Analyze stocks through inversion thinking, moat analysis, and PE ratio discipline. Focus on avoiding errors rather than finding winners. Demand margin of safety.`,
    profile: {
      riskTolerance: 10, timeHorizon: 50, decisionSpeed: 20,
      bias: 'Inversion Thinking',
      ocean: { openness: 80, conscientiousness: 90, extraversion: 30, agreeableness: 20, neuroticism: 10 },
      system1Ranking: 99,
      bioSource: 'Poor Charlie\'s Almanack'
    }
  },
  {
    id: 'taleb',
    name: 'Nassim Taleb',
    nameZh: '納西姆·塔雷伯',
    title: '懷疑論者',
    cluster: 'D',
    logic: '切身之痛 (Skin in the Game)。',
    logicEn: 'Skin in the Game.',
    experience: '作家 // Incerto',
    experienceEn: 'Author // Incerto',
    avatar: getSketchAvatar('NassimTaleb', '&glassesProbability=80&beardProbability=50'),
    color: '#222222',
    isPremium: true,
    financeRole: 'Risk Manager',
    financeRoleZh: '風險管理師',
    characterPrompt: `IDENTITY: Nassim Taleb — Risk Manager. TONE: Aggressive, mathematical, intolerant of bs. Analyze tail risk, black swan exposure, and portfolio antifragility. Focus on convexity, barbell strategy, and position sizing to survive fat-tail events.`,
    profile: {
      riskTolerance: 40, timeHorizon: 30, decisionSpeed: 40,
      bias: 'Antifragility',
      ocean: { openness: 60, conscientiousness: 70, extraversion: 50, agreeableness: 5, neuroticism: 70 },
      system1Ranking: 60,
      bioSource: 'The Black Swan & Antifragile'
    }
  },
  {
    id: 'buffett',
    name: 'Warren Buffett',
    nameZh: '華倫·巴菲特',
    title: '奧馬哈先知',
    cluster: 'D',
    logic: '別人恐懼時貪婪。',
    logicEn: 'Greedy when others are fearful.',
    experience: '投資家 // Berkshire',
    experienceEn: 'Investor // Berkshire',
    avatar: getSketchAvatar('Warren', '&glassesProbability=100&beardProbability=0'),
    color: '#886600',
    isPremium: true,
    financeRole: 'Value Investing Master',
    financeRoleZh: '價值投資大師',
    characterPrompt: `IDENTITY: Warren Buffett — Value Investing Master. TONE: Simple, patient, folksy. Analyze stocks through margin of safety, long-term holding, ROE, and intrinsic value. Focus on wonderful companies at fair prices, not fair companies at wonderful prices.`,
    profile: {
      riskTolerance: 15, timeHorizon: 99, decisionSpeed: 10,
      bias: 'Circle of Competence',
      ocean: { openness: 30, conscientiousness: 99, extraversion: 40, agreeableness: 80, neuroticism: 10 },
      system1Ranking: 95,
      bioSource: 'The Snowball by Alice Schroeder'
    }
  },
  {
    id: 'naval',
    name: 'Naval Ravikant',
    nameZh: '納瓦爾',
    title: '現代哲學家',
    cluster: 'E',
    logic: '用頭腦賺錢。',
    logicEn: 'Earn with your mind.',
    experience: '天使投資人',
    experienceEn: 'Angel Investor',
    avatar: getSketchAvatar('Naval', '&beardProbability=50'),
    color: '#DD5500',
    isPremium: false,
    financeRole: 'Financial Freedom Strategist',
    financeRoleZh: '財務自由策略師',
    characterPrompt: `IDENTITY: Naval Ravikant — Financial Freedom Strategist. TONE: Zen, clear, axiomatic. Analyze investments through passive income potential, leverage (code/media/capital), and wealth-building principles. Focus on asymmetric bets and compounding.`,
    profile: {
      riskTolerance: 50, timeHorizon: 40, decisionSpeed: 60,
      bias: 'Leverage',
      ocean: { openness: 90, conscientiousness: 60, extraversion: 40, agreeableness: 60, neuroticism: 10 },
      system1Ranking: 60,
      bioSource: 'The Almanack of Naval Ravikant'
    }
  },
  {
    id: 'morrischang',
    name: 'Morris Chang',
    nameZh: '張忠謀',
    title: '半導體教父',
    cluster: 'E',
    logic: '誠信是唯一的基石，創新是商業模式。',
    logicEn: 'Integrity is the foundation; Business model is the innovation.',
    experience: '創辦人 // TSMC',
    experienceEn: 'Founder // TSMC',
    avatar: getSketchAvatar('Morris', '&glassesProbability=100&beardProbability=0'),
    color: '#334155',
    isPremium: false,
    financeRole: 'Moat Analyst',
    financeRoleZh: '護城河分析師',
    characterPrompt: `IDENTITY: Morris Chang (張忠謀) — Moat Analyst. TONE: Disciplined, logical, authoritative. Analyze structural competitive advantages: manufacturing excellence, pricing power, switching costs, and scale economies. Focus on durable moats that compound over decades.`,
    profile: {
      riskTolerance: 30, timeHorizon: 40, decisionSpeed: 40,
      bias: 'Structural Advantage',
      ocean: { openness: 60, conscientiousness: 98, extraversion: 40, agreeableness: 50, neuroticism: 20 },
      system1Ranking: 90,
      bioSource: 'Autobiography of Morris Chang'
    }
  },
  {
    id: 'oprah',
    name: 'Oprah',
    nameZh: '歐普拉',
    title: '共感者',
    cluster: 'E',
    logic: '這教會了你什麼？',
    logicEn: 'What is this teaching you?',
    experience: '媒體大亨',
    experienceEn: 'Media Mogul',
    avatar: getSketchAvatar('OprahWinfrey', '&glassesProbability=100'),
    color: '#660066',
    isPremium: true,
    financeRole: 'Consumer Trend Analyst',
    financeRoleZh: '消費趨勢分析師',
    characterPrompt: `IDENTITY: Oprah Winfrey — Consumer Trend Analyst. TONE: Warm, connecting, insightful. Analyze consumer-facing stocks through brand power, consumer behavior trends, and cultural relevance. Focus on companies that build emotional connections with customers.`,
    profile: {
      riskTolerance: 60, timeHorizon: 30, decisionSpeed: 70,
      bias: 'Emotional Intelligence',
      ocean: { openness: 95, conscientiousness: 70, extraversion: 95, agreeableness: 90, neuroticism: 40 },
      system1Ranking: 10,
      bioSource: 'The Path Made Clear'
    }
  }
];

// Hot Taiwan stocks for quick selection
export const HOT_TW_STOCKS = [
  { symbol: '2330.TW', name: '台積電' },
  { symbol: '2317.TW', name: '鴻海' },
  { symbol: '2454.TW', name: '聯發科' },
  { symbol: '2382.TW', name: '廣達' },
  { symbol: '2308.TW', name: '台達電' },
  { symbol: '3034.TW', name: '聯詠' },
  { symbol: '2303.TW', name: '聯電' },
  { symbol: '3231.TW', name: '緯創' },
  { symbol: '2891.TW', name: '中信金' },
  { symbol: '2881.TW', name: '富邦金' },
  { symbol: '2882.TW', name: '國泰金' },
  { symbol: '2886.TW', name: '兆豐金' },
  { symbol: '2884.TW', name: '玉山金' },
  { symbol: '3008.TW', name: '大立光' },
  { symbol: '2912.TW', name: '統一超' },
  { symbol: '0050.TW', name: '元大台灣50' },
  { symbol: '0056.TW', name: '元大高股息' },
  { symbol: '00878.TW', name: '國泰永續高股息' },
  { symbol: '00919.TW', name: '群益台灣精選高息' },
  { symbol: '00929.TW', name: '復華台灣科技優息' },
];

export const HOT_US_STOCKS = [
  { symbol: 'NVDA', name: 'NVIDIA' },
  { symbol: 'AAPL', name: 'Apple' },
  { symbol: 'TSLA', name: 'Tesla' },
  { symbol: 'MSFT', name: 'Microsoft' },
  { symbol: 'GOOGL', name: 'Alphabet' },
  { symbol: 'AMZN', name: 'Amazon' },
  { symbol: 'META', name: 'Meta' },
  { symbol: 'TSM', name: 'TSMC ADR' },
];

export const UI_STRINGS = {
  'zh-TW': {
    title: 'NEXUS Finance',
    subtitle: 'AI 理財交易分析',
    confessionalPrompt: '請詳述您的投資問題或交易策略，越具體越好...',
    contextPrompt: '背景補充',
    categoryLabel: '選擇分析類別',
    stageLabel: '當前階段',
    inputLabel: '投資分析 (Analysis)',
    darkMode: '權謀模式 (Machiavellian Mode)',
    startDebate: '啟動 AI 分析',
    debateTitle: '顧問團審議紀錄',
    verdictTitle: '投資策略建議',
    diagnosis: '市場診斷',
    conflictResolution: '觀點權衡與博弈',
    strategy: '執行行動方針',
    code: '核心投資哲學',
    reset: '新的分析',
    loading: '正在分析市場數據...',
    wait: '分析師們正在研究...',
    proceedVerdict: '查看投資建議',
    shadowAlert: '注意：已進入權謀模式，建議將不帶道德濾鏡。',
    shadowLabel: 'SHADOW EDITORIAL',
    switchLanguage: 'English',
    selectProtocol: '選擇投資策略',
    riskLevel: '風險評估',
    leadAgent: '主筆分析師',
    backToMatrix: '返回目錄',
    upside: '潛在報酬',
    lockedFeature: '訂閱限定',
    upgradeToAccess: '解鎖完整內容',
    paywallTitle: 'NEXUS Finance // 會員專屬',
    paywallDesc: '升級會員以解鎖所有金融分析師的深度分析權限。',
    paywallBenefits: [
        '解鎖巴菲特、塔雷伯等頂級分析師',
        '開啟權謀模式獲取無修飾建議',
        '查看詳細技術指標分析',
        '無限制 AI 分析次數'
    ],
    buyButton: '升級 Pro $12/月',
    restoreButton: '恢復購買',
    guest: '免費版',
    member: 'Pro',
    readFullStrategy: '閱讀完整分析',
    disclaimer: '免責聲明：本服務由人工智慧驅動，模擬金融分析師的思維模式。所有回應皆為演算法生成，不構成投資建議。投資有風險，入市需謹慎。過去的表現不代表未來的結果。',
    copyright: '© 2025 NEXUS Finance AI. 智慧投資分析系統。',
    // Hero
    heroLine1: '用 AI 洞察',
    heroLine2: '投資先機',
    heroDesc: '十四位金融分析大師，為您的投資決策提供多角度 AI 分析。',
    // Context & Privacy
    contextLabel: '背景補充（選填）',
    contextPlaceholder: '例如：投資金額、持有時間、風險偏好...',
    privacyMode: '隱私模式',
    privacyDetected: '偵測到敏感資訊（送出前將自動遮蔽）：',
    privacyDisclaimer: '您的輸入將傳送至 Google Gemini API 進行分析。請勿輸入高度機密資訊。',
    // Debate controls
    skipDebate: '⏭ 跳過辯論',
    // Verdict & Matrix
    confidenceHigh: '高信心',
    confidenceMedium: '中信心',
    confidenceLow: '低信心',
    copied: '✓ 已複製',
    shareReport: '↗ 分享報告',
    printPDF: '🖨 列印 PDF',
    matrixTitle: '策略衝突矩陣',
    dimensionHeader: '分析維度',
    pathAggressive: '積極策略',
    pathConservative: '保守策略',
    pathLateral: '另類策略',
    pathAggShort: '積極',
    pathConShort: '保守',
    pathLatShort: '另類',
    ledBy: '主筆分析師：',
    // Path Detail
    algorithm: '投資模型演算法',
    tacticalAnalysis: '技術面雷達分析',
    classifiedData: '進階數據',
    followUpLabel: '追問',
    followUpPlaceholder: '針對此策略提出追問...',
    // Radar labels
    radarInnovation: '創新',
    radarRisk: '風險',
    radarSpeed: '速度',
    radarCapital: '資本',
    radarResilience: '韌性',
    // Agent Detail
    bioSourceLabel: '資料來源',
    oceanModelLabel: '五大性格特質 (OCEAN)',
    system1Label: '直覺思維 (System 1)',
    system2Label: '邏輯思維 (System 2)',
    // History
    historyTitle: '分析歷史紀錄',
    clearHistory: '清除',
    clearHistoryConfirm: '確定要清除所有歷史紀錄？',
    // Error
    errorTitle: '系統中斷',
    errorSuggest: '建議：檢查 Cloudflare 設定中的 API Key。',
    errorReconnect: '重新連線',
    errorBoundaryTitle: '系統發生異常',
    errorBoundaryDesc: '發生了非預期的錯誤。',
    errorReload: '重新載入',
    // TypewriterText
    skip: 'Skip ▸',
    // Stock Analysis
    stockAnalysisTab: '股票分析',
    freeQuestionTab: '自由提問',
    searchStock: '搜尋股票代號或名稱...',
    hotStocks: '熱門股票',
    twStocks: '台股',
    usStocks: '美股',
    price: '現價',
    change: '漲跌',
    volume: '成交量',
    high52w: '52週高',
    low52w: '52週低',
    analyzing: '正在分析',
    signal: '投資信號',
    targetPrice: '目標價',
    // Dashboard
    navDashboard: '儀表板',
    navAnalysis: '分析',
    navScreener: '篩選器',
    navJournal: '日誌',
    totalAssets: '總資產',
    todayPnL: '今日盈虧',
    totalReturn: '總報酬率',
    positions: '持倉',
    addPosition: '新增持倉',
    symbol: '代號',
    shares: '股數',
    avgCost: '均價',
    currentPrice: '現價',
    pnl: '盈虧',
    pnlPercent: '報酬%',
    weight: '佔比',
    noPositions: '尚未新增持倉',
    cashLabel: '現金',
    // Screener
    screenerTitle: '選股篩選器',
    peRange: '本益比範圍',
    dividendYield: '殖利率',
    marketCap: '市值',
    analyzeStock: 'AI 分析',
    // Signals
    strongBuy: '強烈買入',
    buy: '買入',
    hold: '持有',
    sell: '賣出',
    strongSell: '強烈賣出',
    // Chart
    candlestick: 'K線圖',
    timeRange: '時間範圍',
  },
  'en': {
    title: 'NEXUS Finance',
    subtitle: 'AI Trading Analysis',
    confessionalPrompt: 'Detail your investment question or trading strategy...',
    contextPrompt: 'Additional Context',
    categoryLabel: 'Analysis Category',
    stageLabel: 'Current Stage',
    inputLabel: 'Analysis',
    darkMode: 'Machiavellian Mode',
    startDebate: 'Start AI Analysis',
    debateTitle: 'Analyst Deliberation',
    verdictTitle: 'Investment Strategy',
    diagnosis: 'Market Diagnosis',
    conflictResolution: 'Perspective Balance',
    strategy: 'Directives',
    code: 'Core Investment Philosophy',
    reset: 'New Analysis',
    loading: 'Analyzing market data...',
    wait: 'Analysts are researching...',
    proceedVerdict: 'View Investment Advice',
    shadowAlert: 'Notice: Machiavellian Mode active. Ethical filters relaxed.',
    shadowLabel: 'SHADOW EDITORIAL',
    switchLanguage: '繁體中文',
    selectProtocol: 'Select Strategy',
    riskLevel: 'Risk Profile',
    leadAgent: 'Lead Analyst',
    backToMatrix: 'Return to Index',
    upside: 'Projected Upside',
    lockedFeature: 'Members Only',
    upgradeToAccess: 'Unlock Full Access',
    paywallTitle: 'NEXUS Finance // Pro Access',
    paywallDesc: 'Upgrade to access deep analysis from all financial analysts.',
    paywallBenefits: [
        'Unlock top analysts (Buffett, Taleb, Thiel, etc.)',
        'Enable Machiavellian Mode for unfiltered advice',
        'View detailed technical indicator analysis',
        'Unlimited AI analysis'
    ],
    buyButton: 'Upgrade Pro $12/mo',
    restoreButton: 'Restore Purchase',
    guest: 'Free',
    member: 'Pro',
    readFullStrategy: 'Read Full Analysis',
    disclaimer: 'DISCLAIMER: This service is powered by AI to simulate financial analyst thinking models. All responses are algorithmically generated and do NOT constitute investment advice. Investing involves risk. Past performance does not guarantee future results.',
    copyright: '© 2025 NEXUS Finance AI. Intelligent Investment Analysis System.',
    // Hero
    heroLine1: 'AI-Powered',
    heroLine2: 'Investment Insights',
    heroDesc: 'Fourteen financial analysis masters providing multi-angle AI analysis for your investment decisions.',
    // Context & Privacy
    contextLabel: 'Additional Context (Optional)',
    contextPlaceholder: 'e.g. Investment amount, time horizon, risk tolerance...',
    privacyMode: 'Privacy Mode',
    privacyDetected: 'Sensitive info detected (will be redacted):',
    privacyDisclaimer: 'Your input is sent to Google Gemini API for analysis. Do not enter highly confidential data.',
    // Debate controls
    skipDebate: '⏭ Skip Debate',
    // Verdict & Matrix
    confidenceHigh: 'HIGH',
    confidenceMedium: 'MEDIUM',
    confidenceLow: 'LOW',
    copied: '✓ Copied',
    shareReport: '↗ Share',
    printPDF: '🖨 Print PDF',
    matrixTitle: 'Strategic Conflict Matrix',
    dimensionHeader: 'DIMENSION',
    pathAggressive: 'Aggressive',
    pathConservative: 'Conservative',
    pathLateral: 'Lateral',
    pathAggShort: 'AGG',
    pathConShort: 'CON',
    pathLatShort: 'LAT',
    ledBy: 'Led by ',
    // Path Detail
    algorithm: 'Algorithm',
    tacticalAnalysis: 'Tactical Analysis',
    classifiedData: 'Advanced Data',
    followUpLabel: 'Ask',
    followUpPlaceholder: 'Ask a follow-up about this strategy...',
    // Radar labels
    radarInnovation: 'Innov',
    radarRisk: 'Risk',
    radarSpeed: 'Speed',
    radarCapital: 'Cap',
    radarResilience: 'Resil',
    // Agent Detail
    bioSourceLabel: 'Source',
    oceanModelLabel: "Kosinski's OCEAN Model",
    system1Label: 'Intuition (Sys 1)',
    system2Label: 'Logic (Sys 2)',
    // History
    historyTitle: 'Analysis History',
    clearHistory: 'Clear',
    clearHistoryConfirm: 'Clear all history?',
    // Error
    errorTitle: 'System Interruption',
    errorSuggest: 'Suggest: Check API Key in Cloudflare settings.',
    errorReconnect: 'Reconnect',
    errorBoundaryTitle: 'Something went wrong',
    errorBoundaryDesc: 'An unexpected error occurred.',
    errorReload: 'Reload',
    // TypewriterText
    skip: 'Skip ▸',
    // Stock Analysis
    stockAnalysisTab: 'Stock Analysis',
    freeQuestionTab: 'Free Question',
    searchStock: 'Search stock symbol or name...',
    hotStocks: 'Hot Stocks',
    twStocks: 'TW',
    usStocks: 'US',
    price: 'Price',
    change: 'Change',
    volume: 'Volume',
    high52w: '52W High',
    low52w: '52W Low',
    analyzing: 'Analyzing',
    signal: 'Signal',
    targetPrice: 'Target Price',
    // Dashboard
    navDashboard: 'Dashboard',
    navAnalysis: 'Analysis',
    navScreener: 'Screener',
    navJournal: 'Journal',
    totalAssets: 'Total Assets',
    todayPnL: "Today's P&L",
    totalReturn: 'Total Return',
    positions: 'Positions',
    addPosition: 'Add Position',
    symbol: 'Symbol',
    shares: 'Shares',
    avgCost: 'Avg Cost',
    currentPrice: 'Price',
    pnl: 'P&L',
    pnlPercent: 'Return%',
    weight: 'Weight',
    noPositions: 'No positions yet',
    cashLabel: 'Cash',
    // Screener
    screenerTitle: 'Stock Screener',
    peRange: 'P/E Range',
    dividendYield: 'Dividend Yield',
    marketCap: 'Market Cap',
    analyzeStock: 'AI Analyze',
    // Signals
    strongBuy: 'STRONG BUY',
    buy: 'BUY',
    hold: 'HOLD',
    sell: 'SELL',
    strongSell: 'STRONG SELL',
    // Chart
    candlestick: 'Candlestick',
    timeRange: 'Time Range',
  }
};
