import { Verdict, Language } from '../lib/types';

export interface HistoryEntry {
  id: string;
  query: string;
  verdict: Verdict;
  language: Language;
  timestamp: number;
}

const STORAGE_KEY = 'nexus-council-history';

export function saveToHistory(query: string, verdict: Verdict, language: Language) {
  const entries = getHistory();
  const entry: HistoryEntry = {
    id: Date.now().toString(36),
    query,
    verdict,
    language,
    timestamp: Date.now(),
  };
  entries.unshift(entry);
  // Keep last 20 entries
  const trimmed = entries.slice(0, 20);
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(trimmed));
  } catch (_) {
    // Storage full — remove oldest
    localStorage.setItem(STORAGE_KEY, JSON.stringify(trimmed.slice(0, 10)));
  }
}

export function getHistory(): HistoryEntry[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function clearHistory() {
  localStorage.removeItem(STORAGE_KEY);
}

export function shareVerdict(verdict: Verdict, lang: Language): string {
  const lines = [
    `📋 NEXUS: The Council — ${lang === 'zh-TW' ? '戰略報告' : 'Strategic Report'}`,
    '',
    `📊 ${lang === 'zh-TW' ? '診斷' : 'Diagnosis'}: ${verdict.diagnosis}`,
    '',
    ...verdict.paths.map((p, i) => {
      const icons = ['🔴', '🔵', '🟡'];
      return `${icons[i]} ${p.title}: ${p.description}`;
    }),
    '',
    `— Generated by NEXUS AI Council`,
  ];
  return lines.join('\n');
}
